#!/usr/bin/env bash
# Render the synthetic trade licences to PDF, and emit a manifest.
#
#   ./samples/generate.sh
#
# Every sample in this repo is generated by this script. Nothing here is derived
# from a real licence, and there is no path by which one could be — which is the
# point of generating them rather than sourcing them.
#
# The manifest records the SHA-256 of each rendered file. The stub provider keys
# its canned responses off those hashes, so regenerating the PDFs and updating
# the fixtures is one command rather than two things that drift apart.
set -euo pipefail

cd "$(dirname "$0")/.."

out_dir="public/samples"
manifest="$out_dir/manifest.json"
mkdir -p "$out_dir"

command -v google-chrome >/dev/null 2>&1 || {
  echo "google-chrome not found — it renders the HTML specimens to PDF." >&2
  exit 1
}

# id|label|description — description is shown on the sample buttons in the UI.
samples=(
  "clean|Clean licence|Valid Dubai DED licence. Reads and validates on the first attempt."
  "expired|Expired licence|Extraction is perfect; the licence lapsed in 2024. Reported, never retried."
  "awkward|Awkward layout|Activities set as prose, seal over the text, Abu Dhabi CN format."
)

entries=()

for spec in "${samples[@]}"; do
  IFS='|' read -r id label description <<<"$spec"
  src="samples/templates/$id.html"
  dest="$out_dir/$id.pdf"

  [ -f "$src" ] || { echo "Missing template: $src" >&2; exit 1; }

  google-chrome --headless=new --disable-gpu --no-pdf-header-footer \
    --print-to-pdf="$dest" "file://$(realpath "$src")" >/dev/null 2>&1

  sha=$(sha256sum "$dest" | cut -d' ' -f1)
  bytes=$(stat -c%s "$dest")

  entries+=("$(printf '{"id":"%s","file":"/samples/%s.pdf","label":"%s","description":"%s","sha256":"%s","bytes":%s}' \
    "$id" "$id" "$label" "$description" "$sha" "$bytes")")

  echo "  $dest  ($bytes bytes, ${sha:0:12}…)"
done

# A photographed copy of the awkward specimen: skewed, glare, sensor noise,
# heavy JPEG. This is how a large share of real licences actually arrive, and it
# is the sample that justifies sending bytes to a vision model instead of
# running text extraction first — a text pipeline returns nothing at all here.
scan_dest="$out_dir/scan.jpg"
python3 samples/degrade.py "$out_dir/awkward.pdf" "$scan_dest"

scan_sha=$(sha256sum "$scan_dest" | cut -d' ' -f1)
scan_bytes=$(stat -c%s "$scan_dest")
entries+=("$(printf '{"id":"scan","file":"/samples/scan.jpg","label":"Photographed copy","description":"A phone photo of the same licence: skewed, glare, noise, heavy JPEG. No OCR step — the bytes go to the model.","sha256":"%s","bytes":%s}' \
  "$scan_sha" "$scan_bytes")")

printf '[\n  %s\n]\n' "$(IFS=$',\n  '; echo "${entries[*]}")" >"$manifest"

echo "Wrote $manifest"
