import manifest from '@/../public/samples/manifest.json';
import { activeModel, config } from '@/lib/config';
import { FAULTS } from '@/lib/providers';
import { IntakeDemo, type FaultOption, type Sample } from './components/IntakeDemo';

export const dynamic = 'force-dynamic';

const samples: Sample[] = manifest.map(({ id, file, label, description }) => ({
  id,
  file,
  label,
  description,
}));

const faults: FaultOption[] = Object.entries(FAULTS).map(([name, { label, detail }]) => ({
  name,
  label,
  detail,
}));

export default function Page() {
  return (
    <main className="mx-auto w-full max-w-4xl px-5 py-12 sm:py-16">
      <header className="space-y-4 border-b border-line pb-8">
        <h1 className="text-2xl font-semibold tracking-tight">Document intake agent</h1>
        <p className="max-w-2xl text-sm leading-relaxed text-muted">
          Reads a UAE trade licence, extracts structured fields against a typed schema, validates
          them, and — when validation fails — hands the failures back to the model and tries again.
          Bounded at {config.MAX_ATTEMPTS} attempts, then it stops and asks for a human.
        </p>
        <p className="max-w-2xl text-sm leading-relaxed text-muted">
          Anyone can get a model to return JSON. This shows what happens when it returns the{' '}
          <em>wrong</em> JSON.
        </p>
        <div className="flex flex-wrap gap-x-5 gap-y-1 font-mono text-[11px] text-muted">
          <span>provider {config.provider}</span>
          <span>model {activeModel()}</span>
          <span>max attempts {config.MAX_ATTEMPTS}</span>
          <span>timeout {config.EXTRACTION_TIMEOUT_MS}ms</span>
        </div>
        {config.provider === 'stub' && (
          <p className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-xs leading-relaxed">
            Running on the <strong>stub provider</strong> — canned responses, no model call. This is
            the zero-setup mode, so the loop, the validation rules and the correction step are all
            real; only the model is not. Set <code className="font-mono">LLM_PROVIDER=gemini</code>{' '}
            with an API key to run it live.
          </p>
        )}
      </header>

      <div className="py-8">
        <IntakeDemo samples={samples} faults={faults} />
      </div>

      <footer className="space-y-2 border-t border-line pt-6 text-xs leading-relaxed text-muted">
        <p>
          All four specimens are synthetic, generated by{' '}
          <code className="font-mono">samples/generate.sh</code>. No real licence, entity or
          individual is represented, and no document is stored — the bytes live only for the length
          of the request.
        </p>
      </footer>
    </main>
  );
}
